version: '3.8'
services:
  postgres:
    image: postgres:14.12
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: "oko-freevigilance"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass1234"
    ports:
      - "5432:5432"
    networks:
      - my_network

  web:
    build: .
    ports:
      - "8083:8083"
    volumes:
      - .:/app
    networks:
      - my_network

networks:
  my_network:
    driver: bridge