postgres:
  database: oko-freevigilance
  user: postgres
  password: pass1234
  host: 127.0.0.1
  port: 5432
s3:
  connection_string: http://127.0.0.1:8333
  aws_access_key_id: s3
  aws_secret_access_key: pass1234
