server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: microservice
    static_configs:
      - targets:
          - localhost
        labels:
          job: microservice
          __path__: /var/log/microservice/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            module: module
            request_id: request_id
            path: path
            method: method
            user: user
      - labels:
          level:
          module:
          request_id:
          path:
          method:
          user:
      - timestamp:
          format: Unix
          source: timestamp

